-- Referenzschema für das öffentliche Lese-Archiv.
-- Vor der Ausführung in Supabase prüfen und ein Datenbank-Backup anlegen.

create table if not exists public.ereignisse (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 160),
  location text not null check (char_length(location) between 1 and 180),
  country text check (char_length(country) <= 120),
  continent text check (char_length(continent) <= 80),
  category text not null default 'Ereignis' check (char_length(category) between 1 and 120),
  tags text[] not null default '{}' check (cardinality(tags) <= 24),
  description text not null check (char_length(description) between 1 and 1400),
  significance text check (char_length(significance) <= 1400),
  clue text check (char_length(clue) <= 400),
  longitude double precision not null check (longitude between -180 and 180),
  latitude double precision not null check (latitude between -90 and 90),
  year_start integer check (year_start between -1200 and 2100),
  year_end integer check (year_end between -1200 and 2100),
  date_label text check (char_length(date_label) <= 100),
  image_url text check (image_url is null or image_url ~ '^https://'),
  image_alt text check (char_length(image_alt) <= 240),
  source_url text check (source_url is null or source_url ~ '^https://'),
  difficulty smallint not null default 1 check (difficulty between 1 and 3),
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint valid_year_range check (year_end is null or year_start is null or year_end >= year_start)
);

alter table public.ereignisse enable row level security;
alter table public.ereignisse force row level security;

revoke all on table public.ereignisse from anon;
grant select on table public.ereignisse to anon;

drop policy if exists "Öffentliche Einträge dürfen gelesen werden" on public.ereignisse;
create policy "Öffentliche Einträge dürfen gelesen werden"
on public.ereignisse
for select
to anon
using (true);

-- Absichtlich keine INSERT-, UPDATE- oder DELETE-Policy für anonyme Nutzer*innen.
-- Redaktionelle Änderungen sollten ausschließlich über authentifizierte Rollen erfolgen.
