-- Referenzschema für das öffentliche Lese-Archiv.
-- Vor der Ausführung in Supabase prüfen und ein Datenbank-Backup anlegen.

create table if not exists public.ereignisse (
  id bigint generated by default as identity primary key,
  title text not null,
  location text not null,
  country text,
  continent text,
  category text not null default 'Ereignis',
  tags text[] not null default '{}',
  description text not null,
  significance text,
  clue text,
  longitude double precision not null check (longitude between -180 and 180),
  latitude double precision not null check (latitude between -90 and 90),
  year_start integer check (year_start between -500000 and 2100),
  year_end integer check (year_end between -500000 and 2100),
  date_label text,
  image_url text,
  image_alt text,
  source_url text,
  difficulty smallint not null default 1 check (difficulty between 1 and 3),
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint valid_year_range check (year_end is null or year_start is null or year_end >= year_start)
);

alter table public.ereignisse enable row level security;

drop policy if exists "Öffentliche Einträge dürfen gelesen werden" on public.ereignisse;
create policy "Öffentliche Einträge dürfen gelesen werden"
on public.ereignisse
for select
to anon
using (true);

-- Absichtlich keine INSERT-, UPDATE- oder DELETE-Policy für anonyme Nutzer*innen.
-- Redaktionelle Änderungen sollten ausschließlich über authentifizierte Rollen erfolgen.
